format files

diff --git a/.github/workflows/reusable_build_and_upload_rerun_cli.yml b/.github/workflows/reusable_build_and_upload_rerun_cli.yml
--- a/.github/workflows/reusable_build_and_upload_rerun_cli.yml
+++ b/.github/workflows/reusable_build_and_upload_rerun_cli.yml
@@ -1,191 +1,191 @@
 name: Reusable Rerun CLI build & upload
 
 on:
-  workflow_call:
-    inputs:
-      CONCURRENCY:
-        required: true
-        type: string
-      PLATFORM:
-        required: true
-        type: string
-      ADHOC_NAME:
-        required: false
-        type: string
-        default: ""
-      RELEASE_COMMIT:
-        required: false
-        type: string
-        default: ""
+    workflow_call:
+        inputs:
+            CONCURRENCY:
+                required: true
+                type: string
+            PLATFORM:
+                required: true
+                type: string
+            ADHOC_NAME:
+                required: false
+                type: string
+                default: ""
+            RELEASE_COMMIT:
+                required: false
+                type: string
+                default: ""
 
-  workflow_dispatch:
-    inputs:
-      ADHOC_NAME:
-        required: true
-        type: string
-        description: "Name of the adhoc build, used for upload directory"
-      PLATFORM:
-        type: choice
-        options:
-          - linux
-          - windows
-          - macos-arm
-          - macos-intel
-        description: "Platform to build for"
-        required: true
-      CONCURRENCY:
-        required: false
-        type: string
-        default: "adhoc"
+    workflow_dispatch:
+        inputs:
+            ADHOC_NAME:
+                required: true
+                type: string
+                description: "Name of the adhoc build, used for upload directory"
+            PLATFORM:
+                type: choice
+                options:
+                    - linux
+                    - windows
+                    - macos-arm
+                    - macos-intel
+                description: "Platform to build for"
+                required: true
+            CONCURRENCY:
+                required: false
+                type: string
+                default: "adhoc"
 
 concurrency:
-  group: ${{ inputs.CONCURRENCY }}-build-rerun-cli
-  cancel-in-progress: true
+    group: ${{ inputs.CONCURRENCY }}-build-rerun-cli
+    cancel-in-progress: true
 
 env:
-  PYTHON_VERSION: "3.8"
-  # web_sys_unstable_apis is required to enable the web_sys clipboard API which egui_web uses
-  # https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Clipboard.html
-  # https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html
-  RUSTFLAGS: --cfg=web_sys_unstable_apis --deny warnings
+    PYTHON_VERSION: "3.8"
+    # web_sys_unstable_apis is required to enable the web_sys clipboard API which egui_web uses
+    # https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Clipboard.html
+    # https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html
+    RUSTFLAGS: --cfg=web_sys_unstable_apis --deny warnings
 
-  # See https://github.com/ericseppanen/cargo-cranky/issues/8
-  RUSTDOCFLAGS: --deny warnings --deny rustdoc::missing_crate_level_docs
+    # See https://github.com/ericseppanen/cargo-cranky/issues/8
+    RUSTDOCFLAGS: --deny warnings --deny rustdoc::missing_crate_level_docs
 
 permissions:
-  contents: "read"
-  id-token: "write"
+    contents: "read"
+    id-token: "write"
 
 jobs:
-  set-config:
-    name: Set Config (${{ inputs.PLATFORM }})
-    runs-on: ubuntu-latest
-    outputs:
-      RUNNER: ${{ steps.set-config.outputs.runner }}
-      TARGET: ${{ steps.set-config.outputs.target }}
-      CONTAINER: ${{ steps.set-config.outputs.container }}
-      BIN_NAME: ${{ steps.set-config.outputs.bin_name }}
-    steps:
-      - name: Set runner and target based on platform
-        id: set-config
-        shell: bash
-        run: |
-          case "${{ inputs.PLATFORM }}" in
-            linux)
-              runner="ubuntu-latest-16-cores"
-              target="x86_64-unknown-linux-gnu"
-              container="{'image': 'rerunio/ci_docker:0.10.0'}"
-              bin_name="rerun"
-              ;;
-            windows)
-              runner="windows-latest-8-cores"
-              target="x86_64-pc-windows-msvc"
-              container="null"
-              bin_name="rerun.exe"
-              ;;
-            macos-arm)
-              runner="macos-latest-large" # See https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
-              target="aarch64-apple-darwin"
-              container="null"
-              bin_name="rerun"
-              ;;
-            macos-intel)
-              runner="macos-latest-large" # See https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
-              target="x86_64-apple-darwin"
-              container="null"
-              bin_name="rerun"
-              ;;
-            *) echo "Invalid platform" && exit 1 ;;
-          esac
-          echo "runner=$runner" >> "$GITHUB_OUTPUT"
-          echo "target=$target" >> "$GITHUB_OUTPUT"
-          echo "container=$container" >> "$GITHUB_OUTPUT"
-          echo "bin_name=$bin_name" >> "$GITHUB_OUTPUT"
+    set-config:
+        name: Set Config (${{ inputs.PLATFORM }})
+        runs-on: ubuntu-latest
+        outputs:
+            RUNNER: ${{ steps.set-config.outputs.runner }}
+            TARGET: ${{ steps.set-config.outputs.target }}
+            CONTAINER: ${{ steps.set-config.outputs.container }}
+            BIN_NAME: ${{ steps.set-config.outputs.bin_name }}
+        steps:
+            - name: Set runner and target based on platform
+              id: set-config
+              shell: bash
+              run: |
+                  case "${{ inputs.PLATFORM }}" in
+                    linux)
+                      runner="ubuntu-latest-16-cores"
+                      target="x86_64-unknown-linux-gnu"
+                      container="{'image': 'rerunio/ci_docker:0.10.0'}"
+                      bin_name="rerun"
+                      ;;
+                    windows)
+                      runner="windows-latest-8-cores"
+                      target="x86_64-pc-windows-msvc"
+                      container="null"
+                      bin_name="rerun.exe"
+                      ;;
+                    macos-arm)
+                      runner="macos-latest-large" # See https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
+                      target="aarch64-apple-darwin"
+                      container="null"
+                      bin_name="rerun"
+                      ;;
+                    macos-intel)
+                      runner="macos-latest-large" # See https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
+                      target="x86_64-apple-darwin"
+                      container="null"
+                      bin_name="rerun"
+                      ;;
+                    *) echo "Invalid platform" && exit 1 ;;
+                  esac
+                  echo "runner=$runner" >> "$GITHUB_OUTPUT"
+                  echo "target=$target" >> "$GITHUB_OUTPUT"
+                  echo "container=$container" >> "$GITHUB_OUTPUT"
+                  echo "bin_name=$bin_name" >> "$GITHUB_OUTPUT"
 
-  build-rerun-cli:
-    name: Build rerun-cli (${{ needs.set-config.outputs.RUNNER }})
+    build-rerun-cli:
+        name: Build rerun-cli (${{ needs.set-config.outputs.RUNNER }})
 
-    needs: [set-config]
+        needs: [set-config]
 
-    runs-on: ${{ needs.set-config.outputs.RUNNER }}
-    container: ${{ fromJson(needs.set-config.outputs.CONTAINER) }}
+        runs-on: ${{ needs.set-config.outputs.RUNNER }}
+        container: ${{ fromJson(needs.set-config.outputs.CONTAINER) }}
 
-    steps:
-      - name: Show context
-        shell: bash
-        run: |
-          echo "GITHUB_CONTEXT": $GITHUB_CONTEXT
-          echo "JOB_CONTEXT": $JOB_CONTEXT
-          echo "INPUTS_CONTEXT": $INPUTS_CONTEXT
-          echo "ENV_CONTEXT": $ENV_CONTEXT
-        env:
-          ENV_CONTEXT: ${{ toJson(env) }}
-          GITHUB_CONTEXT: ${{ toJson(github) }}
-          JOB_CONTEXT: ${{ toJson(job) }}
-          INPUTS_CONTEXT: ${{ toJson(inputs) }}
+        steps:
+            - name: Show context
+              shell: bash
+              run: |
+                  echo "GITHUB_CONTEXT": $GITHUB_CONTEXT
+                  echo "JOB_CONTEXT": $JOB_CONTEXT
+                  echo "INPUTS_CONTEXT": $INPUTS_CONTEXT
+                  echo "ENV_CONTEXT": $ENV_CONTEXT
+              env:
+                  ENV_CONTEXT: ${{ toJson(env) }}
+                  GITHUB_CONTEXT: ${{ toJson(github) }}
+                  JOB_CONTEXT: ${{ toJson(job) }}
+                  INPUTS_CONTEXT: ${{ toJson(inputs) }}
 
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ inputs.RELEASE_COMMIT || ((github.event_name == 'pull_request' && github.event.pull_request.head.ref) || '') }}
+            - uses: actions/checkout@v4
+              with:
+                  ref: ${{ inputs.RELEASE_COMMIT || ((github.event_name == 'pull_request' && github.event.pull_request.head.ref) || '') }}
 
-      - name: Set up Rust
-        uses: ./.github/actions/setup-rust
-        with:
-          cache_key: "build-${{ inputs.PLATFORM }}"
-          save_cache: false
-          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
-          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
-          targets: ${{ needs.set-config.outputs.TARGET }}
+            - name: Set up Rust
+              uses: ./.github/actions/setup-rust
+              with:
+                  cache_key: "build-${{ inputs.PLATFORM }}"
+                  save_cache: false
+                  workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
+                  service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
+                  targets: ${{ needs.set-config.outputs.TARGET }}
 
-      - uses: prefix-dev/setup-pixi@v0.4.1
-        with:
-          pixi-version: v0.6.0
+            - uses: prefix-dev/setup-pixi@v0.4.1
+              with:
+                  pixi-version: v0.6.0
 
-      - name: Build web-viewer
-        shell: bash
-        run: |
-          pixi run cargo run --locked -p re_build_web_viewer -- --release
+            - name: Build web-viewer
+              shell: bash
+              run: |
+                  pixi run cargo run --locked -p re_build_web_viewer -- --release
 
-      # This does not run in the pixi environment, doing so
-      # causes it to select the wrong compiler on macos-arm
-      - name: Build rerun-cli
-        shell: bash
-        env:
-          # this stops `re_web_viewer_server/build.rs` from running
-          RERUN_IS_PUBLISHING: true
-        run: |
-          cargo build \
-            --locked \
-            -p rerun-cli \
-            --no-default-features \
-            --features native_viewer,web_viewer \
-            --release \
-            --target ${{ needs.set-config.outputs.TARGET }}
+            # This does not run in the pixi environment, doing so
+            # causes it to select the wrong compiler on macos-arm
+            - name: Build rerun-cli
+              shell: bash
+              env:
+                  # this stops `re_web_viewer_server/build.rs` from running
+                  RERUN_IS_PUBLISHING: true
+              run: |
+                  cargo build \
+                    --locked \
+                    -p rerun-cli \
+                    --no-default-features \
+                    --features native_viewer,web_viewer \
+                    --release \
+                    --target ${{ needs.set-config.outputs.TARGET }}
 
-      - id: "auth"
-        uses: google-github-actions/auth@v1
-        with:
-          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
-          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
+            - id: "auth"
+              uses: google-github-actions/auth@v1
+              with:
+                  workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
+                  service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
 
-      - name: Get sha
-        id: get-sha
-        shell: bash
-        run: |
-          full_commit="${{ inputs.RELEASE_COMMIT || ((github.event_name == 'pull_request' && github.event.pull_request.head.sha) || github.sha) }}"
-          echo "sha=$(echo $full_commit | cut -c1-7)" >> "$GITHUB_OUTPUT"
+            - name: Get sha
+              id: get-sha
+              shell: bash
+              run: |
+                  full_commit="${{ inputs.RELEASE_COMMIT || ((github.event_name == 'pull_request' && github.event.pull_request.head.sha) || github.sha) }}"
+                  echo "sha=$(echo $full_commit | cut -c1-7)" >> "$GITHUB_OUTPUT"
 
-      - name: "Upload rerun-cli (commit)"
-        uses: google-github-actions/upload-cloud-storage@v1
-        with:
-          path: "./target/${{ needs.set-config.outputs.TARGET }}/release/${{ needs.set-config.outputs.BIN_NAME }}"
-          destination: "rerun-builds/commit/${{ steps.get-sha.outputs.sha }}/rerun-cli/${{ inputs.PLATFORM }}"
-          parent: false
+            - name: "Upload rerun-cli (commit)"
+              uses: google-github-actions/upload-cloud-storage@v1
+              with:
+                  path: "./target/${{ needs.set-config.outputs.TARGET }}/release/${{ needs.set-config.outputs.BIN_NAME }}"
+                  destination: "rerun-builds/commit/${{ steps.get-sha.outputs.sha }}/rerun-cli/${{ inputs.PLATFORM }}"
+                  parent: false
 
-      - name: "Upload rerun-cli (adhoc)"
-        if: ${{ inputs.ADHOC_NAME != '' }}
-        uses: google-github-actions/upload-cloud-storage@v1
-        with:
-          path: "./target/${{ needs.set-config.outputs.TARGET }}/release/${{ needs.set-config.outputs.BIN_NAME }}"
-          destination: "rerun-builds/adhoc/${{inputs.ADHOC_NAME}}/rerun-cli/${{ inputs.PLATFORM }}"
-          parent: false
+            - name: "Upload rerun-cli (adhoc)"
+              if: ${{ inputs.ADHOC_NAME != '' }}
+              uses: google-github-actions/upload-cloud-storage@v1
+              with:
+                  path: "./target/${{ needs.set-config.outputs.TARGET }}/release/${{ needs.set-config.outputs.BIN_NAME }}"
+                  destination: "rerun-builds/adhoc/${{inputs.ADHOC_NAME}}/rerun-cli/${{ inputs.PLATFORM }}"
+                  parent: false
diff --git a/.github/workflows/reusable_build_wheels.yml b/.github/workflows/reusable_build_wheels.yml
--- a/.github/workflows/reusable_build_wheels.yml
+++ b/.github/workflows/reusable_build_wheels.yml
@@ -1,169 +1,169 @@
 name: Reusable Build Wheels
 
 on:
-  workflow_call:
-    inputs:
-      CONCURRENCY:
-        required: true
-        type: string
-      MATURIN_FEATURE_FLAGS:
-        required: false
-        type: string
-        default: "--no-default-features --features pypi"
-      PLATFORM:
-        required: true
-        type: string
-      WHEEL_ARTIFACT_NAME:
-        required: false
-        type: string
-        default: ""
-      RELEASE_COMMIT:
-        required: false
-        type: string
-        default: ""
+    workflow_call:
+        inputs:
+            CONCURRENCY:
+                required: true
+                type: string
+            MATURIN_FEATURE_FLAGS:
+                required: false
+                type: string
+                default: "--no-default-features --features pypi"
+            PLATFORM:
+                required: true
+                type: string
+            WHEEL_ARTIFACT_NAME:
+                required: false
+                type: string
+                default: ""
+            RELEASE_COMMIT:
+                required: false
+                type: string
+                default: ""
 
 concurrency:
-  group: ${{ inputs.CONCURRENCY }}-build-wheels
-  cancel-in-progress: true
+    group: ${{ inputs.CONCURRENCY }}-build-wheels
+    cancel-in-progress: true
 
 env:
-  PYTHON_VERSION: "3.8"
-  # web_sys_unstable_apis is required to enable the web_sys clipboard API which egui_web uses
-  # https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Clipboard.html
-  # https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html
+    PYTHON_VERSION: "3.8"
+    # web_sys_unstable_apis is required to enable the web_sys clipboard API which egui_web uses
+    # https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Clipboard.html
+    # https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html
 
-  # TODO(jleibs) --deny warnings causes installation of wasm-bindgen to fail on mac
-  # RUSTFLAGS: --cfg=web_sys_unstable_apis --deny warnings
-  RUSTFLAGS: --cfg=web_sys_unstable_apis
+    # TODO(jleibs) --deny warnings causes installation of wasm-bindgen to fail on mac
+    # RUSTFLAGS: --cfg=web_sys_unstable_apis --deny warnings
+    RUSTFLAGS: --cfg=web_sys_unstable_apis
 
-  # See https://github.com/ericseppanen/cargo-cranky/issues/8
-  RUSTDOCFLAGS: --deny warnings --deny rustdoc::missing_crate_level_docs
+    # See https://github.com/ericseppanen/cargo-cranky/issues/8
+    RUSTDOCFLAGS: --deny warnings --deny rustdoc::missing_crate_level_docs
 
-  # See: https://github.com/marketplace/actions/sccache-action
-  SCCACHE_GHA_ENABLED: "false"
+    # See: https://github.com/marketplace/actions/sccache-action
+    SCCACHE_GHA_ENABLED: "false"
 
 permissions:
-  contents: "read"
-  id-token: "write"
+    contents: "read"
+    id-token: "write"
 
 jobs:
-  # ---------------------------------------------------------------------------
+    # ---------------------------------------------------------------------------
 
-  set-config:
-    name: Set Config (${{ inputs.PLATFORM }})
-    runs-on: ubuntu-latest-16-cores
-    outputs:
-      RUNNER: ${{ steps.set-config.outputs.runner }}
-      TARGET: ${{ steps.set-config.outputs.target }}
-      CONTAINER: ${{ steps.set-config.outputs.container }}
-    steps:
-      - name: Set runner and target based on platform
-        id: set-config
-        shell: bash
-        run: |
-          case "${{ inputs.PLATFORM }}" in
-            linux)
-              runner="ubuntu-latest-16-cores"
-              target="x86_64-unknown-linux-gnu"
-              container="{'image': 'rerunio/ci_docker:0.10.0'}"
-              ;;
-            windows)
-              runner="windows-latest-8-cores"
-              target="x86_64-pc-windows-msvc"
-              container="null"
-              ;;
-            macos-arm)
-              runner="macos-latest-large" # See https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
-              target="aarch64-apple-darwin"
-              container="null"
-              ;;
-            macos-intel)
-              runner="macos-latest-large" # See https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
-              target="x86_64-apple-darwin"
-              container="null"
-              ;;
-            *) echo "Invalid platform" && exit 1 ;;
-          esac
-          echo "runner=$runner" >> "$GITHUB_OUTPUT"
-          echo "target=$target" >> "$GITHUB_OUTPUT"
-          echo "container=$container" >> "$GITHUB_OUTPUT"
+    set-config:
+        name: Set Config (${{ inputs.PLATFORM }})
+        runs-on: ubuntu-latest-16-cores
+        outputs:
+            RUNNER: ${{ steps.set-config.outputs.runner }}
+            TARGET: ${{ steps.set-config.outputs.target }}
+            CONTAINER: ${{ steps.set-config.outputs.container }}
+        steps:
+            - name: Set runner and target based on platform
+              id: set-config
+              shell: bash
+              run: |
+                  case "${{ inputs.PLATFORM }}" in
+                    linux)
+                      runner="ubuntu-latest-16-cores"
+                      target="x86_64-unknown-linux-gnu"
+                      container="{'image': 'rerunio/ci_docker:0.10.0'}"
+                      ;;
+                    windows)
+                      runner="windows-latest-8-cores"
+                      target="x86_64-pc-windows-msvc"
+                      container="null"
+                      ;;
+                    macos-arm)
+                      runner="macos-latest-large" # See https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
+                      target="aarch64-apple-darwin"
+                      container="null"
+                      ;;
+                    macos-intel)
+                      runner="macos-latest-large" # See https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
+                      target="x86_64-apple-darwin"
+                      container="null"
+                      ;;
+                    *) echo "Invalid platform" && exit 1 ;;
+                  esac
+                  echo "runner=$runner" >> "$GITHUB_OUTPUT"
+                  echo "target=$target" >> "$GITHUB_OUTPUT"
+                  echo "container=$container" >> "$GITHUB_OUTPUT"
 
-  # ---------------------------------------------------------------------------
+    # ---------------------------------------------------------------------------
 
-  build-wheels:
-    name: Build Wheels (${{ needs.set-config.outputs.RUNNER }})
+    build-wheels:
+        name: Build Wheels (${{ needs.set-config.outputs.RUNNER }})
 
-    needs: [set-config]
+        needs: [set-config]
 
-    runs-on: ${{ needs.set-config.outputs.RUNNER }}
-    container: ${{ fromJson(needs.set-config.outputs.CONTAINER) }}
+        runs-on: ${{ needs.set-config.outputs.RUNNER }}
+        container: ${{ fromJson(needs.set-config.outputs.CONTAINER) }}
 
-    steps:
-      - name: Show context
-        shell: bash
-        run: |
-          echo "GITHUB_CONTEXT": $GITHUB_CONTEXT
-          echo "JOB_CONTEXT": $JOB_CONTEXT
-          echo "INPUTS_CONTEXT": $INPUTS_CONTEXT
-          echo "ENV_CONTEXT": $ENV_CONTEXT
-        env:
-          ENV_CONTEXT: ${{ toJson(env) }}
-          GITHUB_CONTEXT: ${{ toJson(github) }}
-          JOB_CONTEXT: ${{ toJson(job) }}
-          INPUTS_CONTEXT: ${{ toJson(inputs) }}
+        steps:
+            - name: Show context
+              shell: bash
+              run: |
+                  echo "GITHUB_CONTEXT": $GITHUB_CONTEXT
+                  echo "JOB_CONTEXT": $JOB_CONTEXT
+                  echo "INPUTS_CONTEXT": $INPUTS_CONTEXT
+                  echo "ENV_CONTEXT": $ENV_CONTEXT
+              env:
+                  ENV_CONTEXT: ${{ toJson(env) }}
+                  GITHUB_CONTEXT: ${{ toJson(github) }}
+                  JOB_CONTEXT: ${{ toJson(job) }}
+                  INPUTS_CONTEXT: ${{ toJson(inputs) }}
 
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ inputs.RELEASE_COMMIT || ((github.event_name == 'pull_request' && github.event.pull_request.head.ref) || '') }}
+            - uses: actions/checkout@v4
+              with:
+                  ref: ${{ inputs.RELEASE_COMMIT || ((github.event_name == 'pull_request' && github.event.pull_request.head.ref) || '') }}
 
-      - name: Set up Rust
-        uses: ./.github/actions/setup-rust
-        with:
-          cache_key: "build-${{ inputs.PLATFORM }}"
-          # Cache will be produced by `reusable_checks/rs-lints`
-          save_cache: false
-          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
-          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
+            - name: Set up Rust
+              uses: ./.github/actions/setup-rust
+              with:
+                  cache_key: "build-${{ inputs.PLATFORM }}"
+                  # Cache will be produced by `reusable_checks/rs-lints`
+                  save_cache: false
+                  workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
+                  service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
 
-      - uses: prefix-dev/setup-pixi@v0.4.1
-        with:
-          pixi-version: v0.6.0
+            - uses: prefix-dev/setup-pixi@v0.4.1
+              with:
+                  pixi-version: v0.6.0
 
-      - name: Install dependencies
-        shell: bash
-        run: |
-          pixi run rustup target add ${{ needs.set-config.outputs.TARGET }}
-          pixi run pip install -r rerun_py/requirements-build.txt
+            - name: Install dependencies
+              shell: bash
+              run: |
+                  pixi run rustup target add ${{ needs.set-config.outputs.TARGET }}
+                  pixi run pip install -r rerun_py/requirements-build.txt
 
-      - name: Build web-viewer
-        # only build web-viewer when publishing to pypi
-        if: ${{ contains(inputs.MATURIN_FEATURE_FLAGS, 'pypi') }}
-        shell: bash
-        run: |
-          pixi run cargo run --locked -p re_build_web_viewer -- --release
+            - name: Build web-viewer
+              # only build web-viewer when publishing to pypi
+              if: ${{ contains(inputs.MATURIN_FEATURE_FLAGS, 'pypi') }}
+              shell: bash
+              run: |
+                  pixi run cargo run --locked -p re_build_web_viewer -- --release
 
-      # This does not run in the pixi environment, doing so
-      # causes it to select the wrong compiler on macos-arm
-      - name: Build Wheel
-        uses: PyO3/maturin-action@v1
-        env:
-          # this stops `re_web_viewer_server/build.rs` from running
-          RERUN_IS_PUBLISHING: true
-        with:
-          maturin-version: "0.14.17"
-          manylinux: manylinux_2_31
-          container: off
-          command: build
-          args: |
-            --manifest-path rerun_py/Cargo.toml
-            --release
-            --target ${{ needs.set-config.outputs.TARGET }}
-            ${{ inputs.MATURIN_FEATURE_FLAGS }}
-            --out dist
+            # This does not run in the pixi environment, doing so
+            # causes it to select the wrong compiler on macos-arm
+            - name: Build Wheel
+              uses: PyO3/maturin-action@v1
+              env:
+                  # this stops `re_web_viewer_server/build.rs` from running
+                  RERUN_IS_PUBLISHING: true
+              with:
+                  maturin-version: "0.14.17"
+                  manylinux: manylinux_2_31
+                  container: off
+                  command: build
+                  args: |
+                      --manifest-path rerun_py/Cargo.toml
+                      --release
+                      --target ${{ needs.set-config.outputs.TARGET }}
+                      ${{ inputs.MATURIN_FEATURE_FLAGS }}
+                      --out dist
 
-      - name: Save wheel artifact
-        if: ${{ inputs.WHEEL_ARTIFACT_NAME != '' }}
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{inputs.WHEEL_ARTIFACT_NAME}}
-          path: dist
+            - name: Save wheel artifact
+              if: ${{ inputs.WHEEL_ARTIFACT_NAME != '' }}
+              uses: actions/upload-artifact@v3
+              with:
+                  name: ${{inputs.WHEEL_ARTIFACT_NAME}}
+                  path: dist
